### ISSUE TITLE
The documenation

### ISSUE THREAD

**Issue by PavelVozenilek** [gamblevore/jeebox#1]
I tried to understand what Jeebox is about, and failed.  I have no idea how I could make "Hello World", and how it would look like - executable or interpreted. Those 4 pages on jeebox.org are not enough for me.

It would be really helpful to have small but complete examples, which gradually build knowledge about the language.

It is large amount of work, but it could be done step by step.

**Comment by gamblevore** [comment]
Hi,

Have you looked at http://github.com/gamblevore/jeebox ?

Actually Jeebox is a very simple concept. It's just an AST parser. That you can use for anything. Its pretty much what I said.

I think the problem is that Jeebox isn't like anything else, and people only understand things in terms of "real world example" that they are familiar with. But they are missing this as a real-world-example. So they don't understand it, despite that the concepts are very simple. So they have a problem understanding things in terms of pure concepts...

Anyhow, are you Mac/windows/Linux based? http://github.com/gamblevore/jeebox should compile for Linux/Mac.

If you are windows based, i think Windows has mingw or even a linux-subsystem (By microsoft) you can install. So it may compile there even.

**Comment by gamblevore** [comment]
OK let's go through this bit by bit.

First... thanks for the interest.

Second: "I tried to understand what Jeebox is about, and failed".

It is explained on my website, quite clearly. Over and over. But to summarise: Its a format for describing code, and meaning, but its also extensible meaning it doesn't care what keywords you use.

I think it isn't the lack of pages that is the problem, but a specific blockage in your understanding of things, that is the problem. The only way my website could do better is to understand exactly where in your particular thinking you've gone wrong, and write a page on my website to remedy that. Sort of like a FAQ basically.

i mean, if someone is trying to teach math, and the kid asks... "I don't understand math, you didn't explain it right, what is 2+3? You haven't explained what I am adding? Is this 2 cows + 3 cows? Or 2 eggs + 3 eggs? I don't understand!"

You see? The question you are asking, isnt because i didn't explain it right. Its because theres a blockage in your understanding. And maths teachers will have answers for these sort of things "well... it doesn't matter if its eggs or cows, the numbers still add up the same". But he can't answer those sort of mental blockages without first seeing students WITH those mental blockages.

The same thing with Jeebox. You asked a question that kind of didnt' make sense to ask in the first place. But no problem. Jeebox is extensible, so it doesn't care about eggs or cows, or code or data. It doesn't concern itself with these things.

Basically... to answer your question.

"I have no idea how I could make "Hello World", and how it would look like - executable or interpreted"

Jeebox doesn't run code. If you have made a programming language, or work with one, or are interested in how they work... all programming languages have multiple phases.

* Read files
* Parse files into AST
* Process the AST into objects representing the program
* Create executable from those objects

Jeebox represents the "Parse files into AST" part of the process. It doesn't read the files, or process ASTs, or create executables.

So yes, you can use Jeebox if you were creating your own language. And it would help a lot!

The question you asked is a bit like asking "OK, so I have an XML parser, but I can't see how to make my XML parser display my HTML website?"

Or "OK, So I got a Unicode library, but I can't see how this Unicode library lets me edit MS-word files?"

Its the wrong question.

...

FINALLY. I have about 4 examples in the download already. You didn't mention compiling or running them, so I assume you haven't seen them yet? Or even compiled Jeebox?

**Comment by PavelVozenilek** [comment]
The way I learn something is going step by step, especially when it differs a lot from commonly used tools. 

> Jeebox doesn't run code. If you have made a programming language, or work with one, or are interested in how they work... all programming languages have multiple phases.
> 
> Read files
> Parse files into AST
> Process the AST into objects representing the program
> Create executable from those objects
> Jeebox represents the "Parse files into AST" part of the process. It doesn't read the files, or process ASTs, or create executables.
> 

This should be at the top of readme, instead of the "Jeebox tries to fulfil the goal of describing everything."

**Comment by gamblevore** [comment]
No. Because that would imply that jeebox is about parsing code and making tools for compilers.

But jeebox is basically a universal format that can be used... for ANYTHING.

You don't need to describe code at all, to use jeebox. It can be used to describe english, or data.... or even file-formats like HTML/CSS.

```
html {
    title "hi im an html-like example"
        body {
            img (src="abc.png")
        }
}

```
same concept as HTML. A tree. But this is valid jeebox syntax.

**Comment by gamblevore** [comment]
I could make some use-case examples on the website. And a FAQ.

I think people have a lot of trouble understanding some basic concepts... in general.

People understand XML being extensible.

but somehow trip over and lose that idea when it comes to jeebox. They can't understand an extensible language that can describe code, or data, or meaning. They seem to beleive that if a language can describe code AT ALL... it must only be locked down to one particular language and also must compile it.

But they still understand XML... which is pretty analogous to Jeebox. Its just verbose and awkward compared to Jeebox.

Making a FAQ seems better because its about dealing with people's mental blockages.

Having a mental blockage is not an issue, and it doesn't mean anyone is bad for having it. It took me a little while when I was 16 years old or so to be able to understand the concept of algebra and how its even possible to re-arrange terms and stuff lol.

Its the same deal. Its like a mental leap in complexity to understanding deeper things. Part of growing up, etc.

**Comment by PavelVozenilek** [comment]
> I think people have a lot of trouble understanding some basic concepts... in general.
> 
> People understand XML being extensible.

XML has infinite number of educational resources.

> I could make some use-case examples on the website. And a FAQ.

Yes, please.  Start from the simplest one, have them ordered. 

------------

Looking at the C code, few quick notes:

* `extern "C"` annotation is not needed around implementation, having it around declarations (in header) is enough.
* sized integer definitions from `JB_BasicTypes.h` would be better defined using `<stdint.h>`
* `JB_Alloc.h`:  there's no equivalent of `__builtin_expect` in Visual C++, if there's plan to support this compiler. Likewise, `__attribute__` is not recognized by VC++.

**Comment by gamblevore** [comment]
"XML has infinite number of educational resources."

And an infinite number of people getting PAID to write about it. I've already done the work of 100 people, UNPAID. At a great cost to my life.

I can only do things when I get support for it. Or at least enough interest. But I'm not feeling this interest from you. Its just aggravating.
